### ISSUE TITLE
Technical Specification Peer Review

### ISSUE THREAD

**Issue by Vee-Guz** [calistakerins/CSC-365-Project#1]
Overall, great project specification. It was easy for me to understand and know the goal of your project. 
Some feedback I have:
- You may want to change the [variable name](https://github.com/calistakerins/CSC-365-Project/blob/main/recipes.py#L29) of these variables to represent the string. 
`recipe = "recipe"`
- I think [sorting by time](https://github.com/calistakerins/CSC-365-Project/blob/main/recipes.py#L55) is a great idea. You should consider adding 'time' field when you return each recipe. This way, the user would be able to see the time of each recipe when it is sorted by time.
- You describe [this field](https://github.com/calistakerins/CSC-365-Project/blob/main/ingredients.py#L15) to contain the name of the ingredient and the amount needed to make a recipe, but you are only fetching an ingredient and not a recipe. Maybe you can add the amount needed when you list the recipes. Each recipe that contains that ingredient will also have the amount of the ingredient for that recipe.
- How will you be able to see the id that corresponds to the ingredient? In [this api](https://github.com/calistakerins/CSC-365-Project/blob/main/ingredients.py#L8), you can get information about an ingredient, but how will the user know the `ingr_id` available? Maybe you can do a `list_ingredients` api that allows user to see the ingredients and their id.

**Comment by mtan22** [comment]
made corrections to ingredients.py and revised the spec
